# Site settings
title: Climate-Smart | Stories of Food, Farmers and Solutions
description: > # this means to ignore newlines until "baseurl:"
  This project, through creative multimedia storytelling and literary science writing, is showing the human impact of climate change on our food, while sharing the hope that this research alliance can transform the world's agricultural systems in time.
subject: Education University of California
classification: Web Design

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
